display_name="Legs - A Minmin MiniMoveset"
description="""
Replaces her nair,fair,bair,ftilt and fsmash! Dw she can still recover/attack with up special.
By default, she cannot perform neutral/side/down special, but you can edit the smashline_legs file to set whether you still want her to perform specials (true) or not (false)
Requires Smashline and Skyline
"""
version="1.0"
category="Param"
authors="C#"